[server]
headless = true

[theme]
baseFontSize = 15
baseFontWeight = 400

metricValueFontSize = "1.05rem"
metricValueFontWeight = 600

headingFontSizes = [
    "2rem",
    "1.45rem",
    "1.15rem",
    "1rem",
    "0.9rem",
    "0.85rem"
]

headingFontWeights = [
    650,
    650,
    600,
    600,
    600,
    500
]